In [ ]:
! pip install fastparquet


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 34.1 MB/s eta 0:00:00


In [ ]:
#Uploads compressed parquet file
from google.colab import files
files.upload()

#jupytext --to ipynb Comparative_Cheb_GCN.py
!unzip 342_AllFaultData.zip

Saving 342_AllFaultData.zip to 342_AllFaultData.zip
Archive:  342_AllFaultData.zip
  inflating: 342_AllFaultData.parquet  


In [ ]:
import networkx as nx
import numpy as np
import pandas as pd
import time
import os
import sys

start = time.time()
#Path for linux
path = os.getcwd()
non_noisy_data = pd.read_parquet(path + "/342_AllFaultData.parquet")
silent_columns = ["Bus", " Magnitude1", " Angle1", " Magnitude2", " Angle2", " Magnitude3", " Angle3","Fault_Command","PV_Irradiance","Fault_Type","FaultLocation"]
non_noisy_data = non_noisy_data[silent_columns]
print(non_noisy_data)
print(non_noisy_data.shape)


print(os.getcwd())

no_noise_numpy_data = non_noisy_data.to_numpy()
print(no_noise_numpy_data)
print(no_noise_numpy_data.shape)

sectioner = []
sectioner2 = []
for n in range(len(no_noise_numpy_data)):
   if n%390==0:
       sectioner.append(n)
print(sectioner[0],sectioner[1])
print(len(sectioner))
#
node_features = []
node_labels = []
for n in range(len(sectioner)):
   if n+1 < len(sectioner):
       ####print([sectioner[n],sectioner[n+1]])
       node_features.append([no_noise_numpy_data[sectioner[n]:sectioner[n+1]][:,1:7]])
       node_labels.append(no_noise_numpy_data[sectioner[n]:sectioner[n+1]][0,7:])
   else:
       ####print([sectioner[n],])
       node_features.append([no_noise_numpy_data[sectioner[n]:][:,1:7]])
       node_labels.append(no_noise_numpy_data[sectioner[n]:][0,7:])
print(len(node_features))
#
np.save(path + "/new_data.npy",node_features)
np.save(path + "/new_labels.npy",node_labels)
end = time.time()
print("This took ",-start+end, "seconds")


# numpy_data = np.load(path+"/new_data.npy",allow_pickle = True)
# numpy_data = np.squeeze(numpy_data)
# print(numpy_data)
# print(numpy_data.shape)
# print(numpy_data.size)

# value_data = np.load(path+"/new_labels.npy",allow_pickle = True)
# print(value_data)
# print(value_data.shape)
# print(value_data.size)


           Bus   Magnitude1   Angle1   Magnitude2   Angle2   Magnitude3  \
0           P1      52.7097    -75.9      52.7097    164.1     52.70970   
1           P2      52.7090    -75.9      52.7092    164.1     52.70920   
2           P3      52.7087    -75.9      52.7089    164.1     52.70890   
3           P7      52.7087    -75.9      52.7089    164.1     52.70890   
4           P6       3.0921    -77.5       3.0918    162.5      3.09302   
...        ...          ...      ...          ...      ...          ...   
12167995  S230      95.5083    -45.2      95.2952   -165.4     95.69160   
12167996  S234     146.3490    -43.6     145.9630   -163.5    145.79400   
12167997  S235     143.5330    -43.5     143.3370   -163.5    143.55100   
12167998  S238     143.4050    -45.9     142.6660   -166.0    142.03100   
12167999  S240     139.8630    -45.8     139.3880   -166.1    139.23400   

           Angle3                                      Fault_Command  \
0            44.1  New Faul

In [ ]:

numpy_data = np.load(path+"/new_data.npy",allow_pickle = True)
numpy_data = np.squeeze(numpy_data)
print(numpy_data)
print(numpy_data.shape)
print(numpy_data.size)

value_data = np.load(path+"/new_labels.npy",allow_pickle = True)
print(value_data)
print(value_data.shape)
print(value_data.size)

[[[52.7097 -75.9 52.7097 164.1 52.7097 44.1]
  [52.709 -75.9 52.7092 164.1 52.7092 44.1]
  [52.7087 -75.9 52.7089 164.1 52.7089 44.1]
  ...
  [0.106712 -107.9 0.106748 132.1 0.106717 12.1]
  [0.104521 -109.5 0.104336 130.4 0.104066 10.6]
  [0.10452 -109.5 0.104335 130.4 0.104065 10.6]]

 [[85214.3 -7.3 500115.0 -33.9 416832.0 -5.1]
  [211.546 -91.2 462267.0 -36.1 379804.0 -4.7]
  [211.568 -91.1 462266.0 -36.1 379804.0 -4.7]
  ...
  [454.247 176.4 552.921 -35.0 288.794 90.0]
  [450.326 175.5 548.222 -35.9 286.192 89.1]
  [450.325 175.5 548.221 -35.9 286.191 89.1]]

 [[139420.0 0.0 138954.0 -120.1 139023.0 120.1]
  [139419.0 0.0 138921.0 -120.1 138988.0 120.1]
  [139419.0 0.0 138914.0 -120.1 138980.0 120.1]
  ...
  [252.616 -12.5 255.72 -169.3 102.452 87.5]
  [250.213 -13.6 254.539 -169.7 104.581 86.1]
  [250.529 -13.0 253.277 -170.0 100.968 87.1]]

 ...

 [[138947.0 0.0 138946.0 -120.0 138948.0 120.0]
  [138908.0 0.0 138910.0 -120.0 138911.0 120.0]
  [138899.0 0.0 138902.0 -120.0 138903

In [ ]:
# #For only the 0 PV irradiance scenarios
# import networkx as nx
# import numpy as np
# import pandas as pd
# import time
# import os
# import sys

# start = time.time()
# #Path for linux
# path = os.getcwd()
# non_noisy_data = pd.read_parquet(path + "/342_AllFaultData.parquet")
# silent_columns = ["Bus", " Magnitude1", " Angle1", " Magnitude2", " Angle2", " Magnitude3", " Angle3","Fault_Command","PV_Irradiance","Fault_Type","FaultLocation"]
# non_noisy_data = non_noisy_data[silent_columns]

# #filters out instances with no PV irradiance
# non_noisy_data = non_noisy_data[non_noisy_data['PV_Irradiance'] == 0]
# print(non_noisy_data)
# print(non_noisy_data.shape)


# print(os.getcwd())

# no_noise_numpy_data = non_noisy_data.to_numpy()
# print(no_noise_numpy_data)
# print(no_noise_numpy_data.shape)

# sectioner = []
# sectioner2 = []
# for n in range(len(no_noise_numpy_data)):
#    if n%390==0:
#        sectioner.append(n)
# print(sectioner[0],sectioner[1])
# print(len(sectioner))
# #
# node_features = []
# node_labels = []
# for n in range(len(sectioner)):
#    if n+1 < len(sectioner):
#        ####print([sectioner[n],sectioner[n+1]])
#        node_features.append([no_noise_numpy_data[sectioner[n]:sectioner[n+1]][:,1:7]])
#        node_labels.append(no_noise_numpy_data[sectioner[n]:sectioner[n+1]][0,7:])
#    else:
#        ####print([sectioner[n],])
#        node_features.append([no_noise_numpy_data[sectioner[n]:][:,1:7]])
#        node_labels.append(no_noise_numpy_data[sectioner[n]:][0,7:])
# print(len(node_features))
# #
# np.save(path + "/new_data_with_No_PV.npy",node_features)
# np.save(path + "/new_labels_with_No_PV.npy",node_labels)
# end = time.time()
# print("This took ",-start+end, "seconds")


# # numpy_data = np.load(path+"/new_data.npy",allow_pickle = True)
# # numpy_data = np.squeeze(numpy_data)
# # print(numpy_data)
# # print(numpy_data.shape)
# # print(numpy_data.size)

# # value_data = np.load(path+"/new_labels.npy",allow_pickle = True)
# # print(value_data)
# # print(value_data.shape)
# # print(value_data.size)


           Bus   Magnitude1   Angle1   Magnitude2   Angle2   Magnitude3  \
0           P1      52.7097    -75.9      52.7097    164.1     52.70970   
1           P2      52.7090    -75.9      52.7092    164.1     52.70920   
2           P3      52.7087    -75.9      52.7089    164.1     52.70890   
3           P7      52.7087    -75.9      52.7089    164.1     52.70890   
4           P6       3.0921    -77.5       3.0918    162.5      3.09302   
...        ...          ...      ...          ...      ...          ...   
12166435  S230      94.9459    -46.9      94.7463   -167.1     95.15550   
12166436  S234     145.5080    -45.8     145.1230   -165.7    144.94900   
12166437  S235     142.6890    -45.7     142.5070   -165.8    142.72300   
12166438  S238     142.5920    -47.7     141.8440   -167.7    141.22800   
12166439  S240     139.0530    -47.5     138.5820   -167.9    138.45000   

           Angle3                                      Fault_Command  \
0            44.1  New Faul